name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          make install
      - name: Test with pytest
        run: |
          make test
